---
# tasks file for roles/nginx
- name: install nginx
  become: yes
  package:
    name: nginx
    state: installed 
    
- name: Copy Nginx.conf
  become: yes
  copy:
    src: "./files/nginx.conf"
    dest: "/etc/nginx"
     
- name: enable nginx service
  become: yes
  systemd: 
      name: nginx
      enabled: yes
      
- name: Start nginx service
  become: yes
  service:
      name: nginx
      state: started